@baseUrl = http://localhost:3001

// ARTICLES
###
POST {{baseUrl}}/articles
Content-Type: application/json

{
  "title": "글 테스트입니다",
  "content": "글 테스트입니다.",
  "userId": "6c3a18b0-11c5-4d97-9019-9ebe3c4d1317"
}

###
GET {{baseUrl}}/articles

###
GET {{baseUrl}}/articles?sort=recent&count=10

###
PATCH {{baseUrl}}/articles/87350587-f132-4342-a4da-48a107801085
Content-Type: application/json

{
  "title": "PATCH 게시글 제목입니다",
  "content": "PATCH 테스트 본문입니다."
}

###
DELETE {{baseUrl}}/articles/5ab3b753-5545-4a44-a990-28d8bfa9d11f



// COMMENTS

###
GET {{baseUrl}}/comments


###
GET {{baseUrl}}/comments/10


###
POST {{baseUrl}}/articles/1418fc5e-7ab9-4f06-8da1-9972f128f122/comments
Content-Type: application/json

{
  "userId": "6c3a18b0-11c5-4d97-9019-9ebe3c4d1317",
  "content": "코멘트 테스트입니다."
}

###
PATCH {{baseUrl}}/comments/8
Content-Type: application/json

{
  "content": "PATCH 코멘트 테스트입니다"
}

###
DELETE {{baseUrl}}/comments/12


// 회원가입

### 잘못된 이메일 형식
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "wrong-email",
  "nickname": "gildong",
  "password": "12345678"
}

### 정상 회원가입
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "nickname": "테스트",
  "password": "password1234"
}


// 로그인

### 로그인 실패 - 잘못된 비밀번호
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "wrongpassword"
}

### 로그인 성공
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password1234"
}

### 현재 사용자 조회 실패 - 토큰 없음
GET {{baseUrl}}/auth/me

### 현재 사용자 조회 성공
GET {{baseUrl}}/auth/me
Authorization: Bearer {{login.response.body.$.accessToken}}


// 상품 등록
### 상품 등록 실패 - 토큰 없음
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "맥북 에어",
  "description": "깨끗하게 사용했습니다.",
  "price": 800000,
  "tags": ["노트북", "애플"],
  "images": []
}

### 상품 등록
POST {{baseUrl}}/products
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

{
  "name": "맥북 에어2",
  "description": "깨끗하게 사용했습니다.",
  "price": 8000000,
  "tags": ["노트북", "애플"],
  "images": []
}

###
GET {{baseUrl}}/products

###
GET {{baseUrl}}/products?page=1&pageSize=10&orderBy=favorite


### 상품 목록 조회
GET {{baseUrl}}/products?page=1&pageSize=10&orderBy=recent&keyword=맥북

### 
GET {{baseUrl}}/products/bc8005a0-61ff-43a7-97f0-76ef09603318


###
PATCH {{baseUrl}}/products/bc8005a0-61ff-43a7-97f0-76ef09603318
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

{
  "price": 790000
}


###
DELETE {{baseUrl}}/products/6a3e18c6bba30124a3a4ac21

