@baseUrl = http://localhost:3001

GET {{baseUrl}}/products

###

GET {{baseUrl}}/products?sort=recent&count=10

###

### 
GET {{baseUrl}}/products/6a3e18c6bba30124a3a4ac21

###
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "테스트 제품",
  "description": "테스트 기록 본문 입니다",
  "price": 8900
}

###
PATCH {{baseUrl}}/products/6a3e1a82bba30124a3a4ac22
Content-Type: application/json

{
  "name": "PATCH 테스트 제목입니다",
  "description": "PATCH 테스트 본문입니다.",
  "price": 5123
}

###
DELETE {{baseUrl}}/products/6a3e18c6bba30124a3a4ac21



// ARTICLES
###
POST {{baseUrl}}/articles
Content-Type: application/json

{
  "title": "글 테스트입니다",
  "content": "글 테스트입니다.",
  "userId": "6c3a18b0-11c5-4d97-9019-9ebe3c4d1317"
}

###
GET {{baseUrl}}/articles

###
GET {{baseUrl}}/articles?sort=recent&count=10

###
PATCH {{baseUrl}}/articles/87350587-f132-4342-a4da-48a107801085
Content-Type: application/json

{
  "title": "PATCH 게시글 제목입니다",
  "content": "PATCH 테스트 본문입니다."
}

###
DELETE {{baseUrl}}/articles/5ab3b753-5545-4a44-a990-28d8bfa9d11f



// COMMENTS

###
GET {{baseUrl}}/comments


###
GET {{baseUrl}}/comments/10


###
POST {{baseUrl}}/articles/1418fc5e-7ab9-4f06-8da1-9972f128f122/comments
Content-Type: application/json

{
  "userId": "6c3a18b0-11c5-4d97-9019-9ebe3c4d1317",
  "content": "코멘트 테스트입니다."
}

###
PATCH {{baseUrl}}/comments/8
Content-Type: application/json

{
  "content": "PATCH 코멘트 테스트입니다"
}

###
DELETE {{baseUrl}}/comments/12


// 회원가입

### 잘못된 이메일 형식
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "wrong-email",
  "nickname": "gildong",
  "password": "12345678"
}

### 정상 회원가입
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "nickname": "테스트",
  "password": "password1234"
}


// 로그인

### 로그인 실패 - 잘못된 비밀번호
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "wrongpassword"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password1234"
}