POST http://localhost:3000/products/509206ef-072d-49ae-903a-dbb16b1cdc4b/comments
Content-Type: application/json

{
  "content": ""
}

### POST article comment 등록 테스트
POST http://localhost:3000/articles/c8f0f356-288d-45b6-a4d9-d045cbc4a4f9/comments
Content-Type: application/json

{
  "content": "게시글 댓글 validator 테스트 ^.^"
}

### GET product comment 조회 테스트
GET http://localhost:3000/products/509206ef-072d-49ae-903a-dbb16b1cdc4b/comments

### GET article comments 목록 조회
GET http://localhost:3000/articles/c8f0f356-288d-45b6-a4d9-d045cbc4a4f9/comments

### PATCH comment 수정 테스트
PATCH http://localhost:3000/comments/274d95e4-cf88-4dc8-a3f8-34b1b167fe0e
Content-Type: application/json

{
  "content": "허용 필드만 수정되는지 확인",
  "id": "hacked-id",
  "createdAt": "2000-01-01",
  "productId": "fake-product-id",
  "articleId": "fake-article-id"
}

### DELETE comment 삭제 테스트
DELETE http://localhost:3000/comments/916794f0-4c68-4389-99ef-de3a388a4ec1


### GET product comments - cascade 삭제 테스트 조회
GET http://localhost:3000/products/f085e905-260e-45cf-946d-a51b64f7d77b/comments?limit=10

### GET article comments - cascade 삭제 전 확인
GET http://localhost:3000/articles/1756bcf0-eb30-4041-bdf8-e30a9f13d5b1/comments?limit=10

