#/*********** products ***********/
GET http://localhost:3000/products?sort=oldest

###
GET http://localhost:3000/products/3a7e9f21-b4c8-4df5-9a2e-6c0f8d31b572

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "아이폰 미니 13",
  "description": "아이폰 미니 13 팔아요! 사용감 있습니다.",
  "price": "십만원",
  "tags": ["애플", "아이폰"]
}

###
PATCH http://localhost:3000/products/00891d0f-99e3-491d-b27e-5a417556be8e
Content-Type: application/json

{
  "price": 1200000
}

###
DELETE http://localhost:3000/products/00891d0f-99e3-491d-b27e-5a417556be8e

#/*********** articles ***********/
###
GET http://localhost:3000/articles?limit=5&sort=oldest

###
GET http://localhost:3000/articles/a7c3e9f1-4b62-4d8a-91f0-3e6b2c7d5a84

###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "대학생 필기용 아이패드 추천해주세요!",
  "content": "가성비 아이패드 추천해주세요! 필기, 영상보는 용도로 사용할 거예용"
}

###
PATCH http://localhost:3000/articles/38bc3162-8bd7-408e-99c7-7476d2ffac16
Content-Type: application/json

{
  "title": "아이패드 추천"
}

###
DELETE http://localhost:3000/articles/38bc3162-8bd7-408e-99c7-7476d2ffac16

#/*********** comments ***********/
###
GET http://localhost:3000/products/0a6f3c9d-8b21-4e75-96d4-3f1a7c0e5b82/comments

###
GET http://localhost:3000/articles/1f6e9c2a-8d74-4b53-a7c0-5e3d9f1b6248/comments

###
POST http://localhost:3000/products/3a7e9f21-b4c8-4df5-9a2e-6c0f8d31b572/comments
Content-Type: application/json

{
  "content": "아직 거래 가능한가요?"
}

###
POST http://localhost:3000/articles/d8f1b3a6-7c25-4e90-9a4b-1f6c8e2d5730/comments
Content-Type: application/json

{
  "content": "학습용이면 에어 추천해요!"
}

###
PATCH http://localhost:3000/comments/973285f3-c2b0-439f-a143-225899caa23e
Content-Type: application/json

{
  "content": "거래 가능할까요?"
}

###
DELETE http://localhost:3000/comments/973285f3-c2b0-439f-a143-225899caa23e