### 상품 목록 조회
GET http://localhost:3000/products


### 상품 등록
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "테스트 상품",
  "description": "CRUD 테스트용 상품입니다.",
  "price": 10000,
  "tags": ["test", "mongo"]
}


### 상품 상세 조회
GET http://localhost:3000/products/b955d93b-47bb-4917-8fbd-99f4fc6d4a08


### 상품 수정
PATCH http://localhost:3000/products/b955d93b-47bb-4917-8fbd-99f4fc6d4a08
Content-Type: application/json

{
  "name": "수정된 테스트 상품",
  "tags": ["test", "migration"]
}


### 상품 삭제
DELETE http://localhost:3000/products/b955d93b-47bb-4917-8fbd-99f4fc6d4a08


### 삭제 후 상세 조회 확인
GET http://localhost:3000/products/b955d93b-47bb-4917-8fbd-99f4fc6d4a08