### 회원가입
POST http://localhost:3001/auth/signUp
Content-Type: application/json

{
  "email": "leecoding@gmail.com",
  "password": "12341234",
  "passwordConfirmation": "12341234",
  "nickname": "이코딩"
}

### 로그인
POST http://localhost:3001/auth/signIn
Content-Type: application/json

{
  "email": "leecoding@gmail.com",
  "password": "12341234"
}

### 토큰 refresh
POST http://localhost:3001/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc4NzYzNTYyOSwiZXhwIjoxNzg4ODQ1MjI5fQ.9091Tac83mAOJAt8NOJ135sdV0iAZ5eSAsLD6PzVCSI"
}